### ISSUE TITLE
notes on getting this script to work

### ISSUE THREAD

**Issue by rjwalters** [iscilyas/zyxel-modem-backup-extract#2]
It was a little complicated to get this to work so I wanted to share some notes here for others who may be struggling. **I was ultimately able to get the data I needed from my Zyxel backup file!**

Getting access to the router to download the configuration backup required some searching to find default login credentials (admin/turktelekom) so that I could log into 192.168.1.1

 `python-lzw` requires Python 2.6 but it's quite frustrating to work with such an old version version - so I ended up breaking the script into two pieces:

* The first script just parses the configuration file and saves the resulting xml text to a file. To get this working I removed `argparse` and hard coded values, and I (eventually) copied the lzw code directly into this script from [python-lzw](https://github.com/joeatwork/python-lzw/blob/master/lzw/__init__.py) rather than mess with installing the package for v2.6 -- otherwise you have to install `pip` from a whl file, deal with `setuptools`, etc and it's a pain. 

The xml file can saved after `decoder.decodepages` runs successfully:

```python
    with open("r.txt", "wb") as f:
        for c in r:
            f.write(c)
```

* My second script isolated the `lxml` parser code and loads the decompressed data from the file we saved. This script can be run in python 3 so that it is easier to install and the `lxml` library.

Loading the file to recover `r` can be done like this:

```python
    r = ""
    for c in list(open("r.txt", 'rb').read()):
        r += chr(c)
```

**Comment by Ertavf** [comment]
Here are my notes on how I used the Python2.7 Docker image.

Open [Cloud Shell](https://shell.cloud.google.com/)

upload .conf file
![image](https://user-images.githubusercontent.com/1387842/218652654-598c14ae-2f31-46ca-9245-dfde4f0f8542.png)


```
# copy&paste all below
git clone https://github.com/iscilyas/zyxel-modem-backup-extract.git zyxel-extract
mv configuration-backupsettings.conf zyxel-extract/
docker run --rm -it -v $(pwd)/zyxel-extract:/mnt/z python:2.7.18-stretch /bin/bash 
```
![image](https://user-images.githubusercontent.com/1387842/218651531-331846be-58fc-475c-83dc-de174cbd9fbc.png)

```
cd /mnt/z
pip install lxml
pip install lzw
python ./zyxel-extract.py configuration-backupsettings.conf
```
![image](https://user-images.githubusercontent.com/1387842/218652387-7c760a6a-3860-4eac-9ed0-1d8648850b2e.png)

**Comment by iscilyas** [comment]
> `python-lzw` requires Python 2.6 but it's quite frustrating to work with such an old version version - so I ended up breaking the script into two pieces:

i just wrote this code and threw it out there... yeah you're right python 2.6 is prehistoric and probably i'd cringe to see my code now (which is why i'm not going to look at it)...

the main goal was to save others the many  hours it took me to figure out how to do this and to give  non-programmers a way to follow instructions and get the answer they're looking for. having said that, i think you have a point in that it's not really all that easy to setup...

care to add a PR with your python 3 changes?

**Comment by iscilyas** [comment]
> Here are my notes on how I used the Python2.7 Docker image.

thanks for posting that! technically it should be possible with windows as well (well... i think so. i wrote it on linux but python should be python, right?)

**Comment by iscilyas** [comment]
erm... @rjwalters @Ertavf ... `python-lzw` doesn't require python 2.7 (per the "instructions" site... "lzw currently requires python 2.7 or python 3.4 to run.")

**Comment by sonerduymaz** [comment]
Traceback (most recent call last):
  File "./zyxel-extract.py", line 194, in <module>
    log.info(r.decode('utf-8'))
  File "/usr/local/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x82 in position 87142: invalid start byte

any idea?

**Comment by Ertavf** [comment]
@sonerduymaz 
I don't remember at all, and I don't have a conf file to test. 
I see that you used Python 2.7 in the error message you sent, it should have worked.
If you want me to try as well, you can temporarily share your conf file attaching here.

**Comment by sonerduymaz** [comment]
> @sonerduymaz I don't remember at all, and I don't have a conf file to test. I see that you used Python 2.7 in the error message you sent, it should have worked. If you want me to try as well, you can temporarily share your conf file attaching here.


hocam merhaba, okulumuzun acil modemini degistirecegiz fakat ppoe sifresine ulasamiyoruz, ttnet e yazi gondermek icinde zamanimiz yok dosyayi size direk nasil gonderebilirim.

**Comment by Ertavf** [comment]
sürükle bırak yaparak buraya yükleyebilirsin.

**Comment by sonerduymaz** [comment]
[configuration-backupsettings.zip](https://github.com/iscilyas/zyxel-modem-backup-extract/files/12542974/configuration-backupsettings.zip)

**Comment by Ertavf** [comment]
~~https://meet.google.com/uec-smfp-izz~~
hallettik, zyxel'in verdigi xml hatalı imiş,
@iscilyas videodaki teşekkürler sana, bi iki gune bu videonun görünürlüğünü değiştiririm, yetişemezsen yaz: https://youtu.be/hYtXGi2jlEQ
